version: 2.1

orbs:
  android: circleci/android@2.5.0

jobs:
  build-apps:
    executor:
      name: android/android-machine
      resource-class: large
      tag: default
    steps:
      - checkout
      - run: ./gradlew assemble
      - store_artifacts:
          path: composeApp/build/outputs/
          destination: build-outputs

  build-ios:
    macos:
      xcode: "15.2.0"
    steps:
      - checkout
      - run:
          name: Setup Corretto JDK 17
          command: |
            brew install corretto17
            echo 'export JAVA_HOME=$(/usr/libexec/java_home -v17)' >> $BASH_ENV
            source $BASH_ENV
      - run:
          name: Build Multiplatform project
          command: ./gradlew assemble

workflows:
  build-all:
    jobs:
      - build-apps
      - build-ios
