version: 2.1

orbs:
  android: circleci/android@2.5.0

jobs:
  build-android:
    executor:
      name: android/android-machine
      resource-class: large
      tag: default
    steps:
      - checkout
      - run: ./gradlew build composeApp:android

  build-ios:
    macos:
      xcode: 15.2.0
    steps:
      - checkout
      - run: ./gradlew build composeApp:ios

workflows:
  build-all:
    jobs:
      - build-android
      - build-ios
